### ISSUE TITLE
Conda installation

### ISSUE THREAD

**Issue by snayfach** [zjshi/Maast#1]
You should be able to add the python dependencies to the maast bioconda recipe. That way you only need to run: `conda install -c bioconda maast`. Is that doable?

**Comment by druvus** [comment]
@snayfach I have added the latest version of Maast to Bioconda. Please check if it is working as expected.

**Comment by zjshi** [comment]
@druvus THANKS! Just a quick question: how do I update Maast in the Bioconda channel when needed, would it be similar to the way I update it in my personal channel?
