### ISSUE TITLE
Missing field names on concat_allele.aln.mat

### ISSUE THREAD

**Issue by snayfach** [zjshi/Maast#10]
I assume the field names are the same as the row names, but helpful to include for downstream analysis

**Comment by zjshi** [comment]
Yes, they should be. The matrix is a direct output of FastTreeMP. Might be difficult to make native change. However, this might be done using the following one liner: `cat <(head -n 1 /path/to/concat_allele.aln.mat) <(cut -d' ' -f1 /path/to/concat_allele.aln.mat | sed '1d' | tr '\n' ' ' | sed 's/^/row_name /g' | sed 's/ $/\n/') <(sed '1d' /path/to/concat_allele.aln.mat)`

**Comment by snayfach** [comment]
Can you add a post-processing step to add field names? That would make it super easy to read the matrix file into R or python
