### ISSUE TITLE
Add wiki

### ISSUE THREAD

**Issue by snayfach** [zjshi/Maast#11]
See MIDAS2 as an example: https://github.com/czbiohub/MIDAS2.0/wiki/. Here's another example: https://github.com/soedinglab/MMseqs2/wiki. Think something like this is doable?

This makes it super easy to go right where you want to go without scrolling the whole document. Usually I go straight to installation or quickstart to get the program installed and running on a test dataset as quickly as possible.

**Comment by zjshi** [comment]
Yes, sounds great, just added that.
