### ISSUE TITLE
Add readme to output directory

### ISSUE THREAD

**Issue by snayfach** [zjshi/Maast#14]
I find it really nice when there's a readme included in the output folder that describes the contents. You've named the files well, but can be nice to have them explained in a file

`$ ls`

> check_fna_paths.list  core_snps.vcf  kmer_db.bin    logfile          reference.fna       tag_msa.fna     temp
> coords.tsv            gt_results     kmer_prof.tsv  nr_kmer_set.tsv  selected_kmers.tsv  tag_paths.list

**Comment by zjshi** [comment]
I like this idea. Instead of adding an readme file, I made the program to print it instead.
