### ISSUE TITLE
VCF file format

### ISSUE THREAD

**Issue by snayfach** [zjshi/Maast#15]
Are we sure that the current format is correct? Do you know anyone who uses VCF files? Maybe they could test it out to make sure it works with standard programs.

One easy fix is to update the source field:
> ##source=https://github.com/snayfach/snpMLST

I'm not sure what the differences are, but there's not a 4.2 version of the format: https://samtools.github.io/hts-specs/VCFv4.2.pdf

It's not clear what nucleotides the 4 genotypes refer to: 

> GP1:GP2:GP3:GP4

**Comment by zjshi** [comment]
Applied the easy fix as well as improved `GP1:GP2:GP3:GP4` description.
