### ISSUE TITLE
Tag a release? 

### ISSUE THREAD

**Issue by druvus** [zjshi/Maast#19]
Could you please tag a github release? It would be helpful to have downloadable tagged releases to refer to. It is needed for the Bioconda recipe.

**Comment by druvus** [comment]
To clarify it would be great to have a tagged release here: https://github.com/zjshi/Maast/releases

**Comment by zjshi** [comment]
I will close the issue for now, but please feel free to reopen it if any changes are needed.

**Comment by zjshi** [comment]
Hi @druvus , I have just tagged a new release of Maast (v1.0.8) for a small but critical bug fix. Could you please help update the version hosted in Bioconda channel? Thanks a lot!
