### ISSUE TITLE
Small example dataset for testing

### ISSUE THREAD

**Issue by snayfach** [zjshi/Maast#3]
Could you provide a download link to a small dataset that could be used for testing? Maybe a tarball of 100 E. coli genomes, or something like that. That would make it really easy to test the code.

**Comment by zjshi** [comment]
Sure, hopefully this smaller set helps: https://fileshare.czbiohub.org/s/EFLBW86Ara7xZtn

**Comment by snayfach** [comment]
Thanks! let me know when you're ready for the next round of testing.

**Comment by zjshi** [comment]
Yes, let's kick the next round off.

**Comment by snayfach** [comment]
`$ Maast/maast end_to_end --in-dir ./101346 --out-dir ./101346_out`

> skip ./101346/OM08-11_1.fastq.gz: not fasta format
> skip ./101346/AM31-23_1.fastq.gz: not fasta format
> skip ./101346/AF25-38AC_1.fastq.gz: not fasta format
> skip ./101346/TM07-1_1.fastq.gz: not fasta format
> skip ./101346/AM23-11_1.fastq.gz: not fasta format
> skip ./101346/TF09-22_1.fastq.gz: not fasta format
> skip ./101346/AF36-11BH_1.fastq.gz: not fasta format
> skip ./101346/AF21-53_1.fastq.gz: not fasta format
> skip ./101346/OM08-11_1.fastq.gz: not fasta format
> skip ./101346/AM31-23_1.fastq.gz: not fasta format
> skip ./101346/AF25-38AC_1.fastq.gz: not fasta format
> skip ./101346/TM07-1_1.fastq.gz: not fasta format
> skip ./101346/AM23-11_1.fastq.gz: not fasta format
> skip ./101346/TF09-22_1.fastq.gz: not fasta format
> skip ./101346/AF36-11BH_1.fastq.gz: not fasta format
> skip ./101346/AF21-53_1.fastq.gz: not fasta format

**Comment by snayfach** [comment]
Also I think 300 genomes is a bit too many for a quick test. As a user I'd like the program to run in < 1 minute , just so I can see how it works, what the output looks like, etc.

**Comment by snayfach** [comment]
Maybe you could have two examples, one for genome-based and one for reads-based genotyping? It's a little confusing to include both kinds of data in the same folder

**Comment by zjshi** [comment]
Hmm... https://fileshare.czbiohub.org/s/EFLBW86Ara7xZtn after download has a name of `101346_small.tar.gz` and only have 150 fastas and 3 fastqs. Could you confirm it?

Yeah, supplying two data type in the same folder is a feature. It does not matter to Maast whether the input folder contain only genomes, reads or both. I edited README to clarify it.

**Comment by zjshi** [comment]
Anyway, try this one instead: `https://fileshare.czbiohub.org/s/tWdDA8BLrpGNEQY`, thanks.
